## Table Of Contents
* [1- Loading the Dataset](#1-LoadingtheDataset)
* [2- Data-Preprocessing](#Data-Preprocessing)

<h1>1- Loading the Dataset </h1>

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv(r'dataset//cell2celltrain.csv', delimiter = ",",  header = 0, index_col = 0)

In [4]:
data.shape


(51047, 57)

In [5]:
data.info()


<class 'pandas.core.frame.DataFrame'>
Index: 51047 entries, 3000002 to 3399994
Data columns (total 57 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Churn                      51047 non-null  object 
 1   MonthlyRevenue             50891 non-null  float64
 2   MonthlyMinutes             50891 non-null  float64
 3   TotalRecurringCharge       50891 non-null  float64
 4   DirectorAssistedCalls      50891 non-null  float64
 5   OverageMinutes             50891 non-null  float64
 6   RoamingCalls               50891 non-null  float64
 7   PercChangeMinutes          50680 non-null  float64
 8   PercChangeRevenues         50680 non-null  float64
 9   DroppedCalls               51047 non-null  float64
 10  BlockedCalls               51047 non-null  float64
 11  UnansweredCalls            51047 non-null  float64
 12  CustomerCareCalls          51047 non-null  float64
 13  ThreewayCalls              51047 non-null  

In [6]:
data.head()

Churn  MonthlyRevenue  MonthlyMinutes  TotalRecurringCharge  \
CustomerID                                                               
3000002      Yes           24.00           219.0                  22.0   
3000010      Yes           16.99            10.0                  17.0   
3000014       No           38.00             8.0                  38.0   
3000022       No           82.28          1312.0                  75.0   
3000026      Yes           17.14             0.0                  17.0   

            DirectorAssistedCalls  OverageMinutes  RoamingCalls  \
CustomerID                                                        
3000002                      0.25             0.0           0.0   
3000010                      0.00             0.0           0.0   
3000014                      0.00             0.0           0.0   
3000022                      1.24             0.0           0.0   
3000026                      0.00             0.0           0.0   

            PercChangeMinutes  PercChangeRevenues  DroppedCalls  ...  \
CustomerID                                                       ...   
3000002                -157.0               -19.0           0.7  ...   
3000010                  -4.0                 0.0           0.3  ...   
3000014                  -2.0                 0.0           0.0  ...   
3000022                 157.0                 8.1          52.0  ...   
3000026                   0.0                -0.2           0.0  ...   

            ReferralsMadeBySubscriber  IncomeGroup  OwnsMotorcycle  \
CustomerID                                                           
3000002                             0            4              No   
3000010                             0            5              No   
3000014                             0            6              No   
3000022                             0            6              No   
3000026                             0            9              No   

            AdjustmentsToCreditRating  HandsetPrice  MadeCallToRetentionTeam  \
CustomerID                                                                     
3000002                             0            30                      Yes   
3000010                             0            30                       No   
3000014                             0       Unknown                       No   
3000022                             0            10                       No   
3000026                             1            10                       No   

            CreditRating  PrizmCode    Occupation  MaritalStatus  
CustomerID                                                        
3000002        1-Highest   Suburban  Professional             No  
3000010         4-Medium   Suburban  Professional            Yes  
3000014           3-Good       Town        Crafts            Yes  
3000022         4-Medium      Other         Other             No  
3000026        1-Highest      Other  Professional            Yes  

[5 rows x 57 columns]

<h1> 2- Data-Preprocessing </h1> 

<b>checking if there are rows that contain empty enteries</b>

In [7]:
rows_without_missing_data = data.dropna()

print(f"all rows: {data.shape}") 
print(f"rows without missing data: {rows_without_missing_data.shape}")
rows_w_missing_data=data.shape[0]-rows_without_missing_data.shape[0]


all rows: (51047, 57)
rows without missing data: (49752, 57)


In [8]:
rows_w_missing_data=data.shape[0]-rows_without_missing_data.shape[0]

In [9]:
rows_w_missing_data

1295

<b>checking that values of dependent variable (Churn) contains only either Yes or No  </b>

In [10]:
data['Churn'].unique()

array(['Yes', 'No'], dtype=object)

<b> Confirmed. no mistakes in data entry for this Class</b>

In [ ]:
<h3>There are columns in the data that are of type "object" and it is unclear what their real data tuy</h3>

In [15]:
for column in data.columns:
    if len(data[column].unique()) <= 10:
        print(data[column].unique())

['Yes' 'No']
['No' 'Yes']
['No' 'Yes']
['Yes' 'No']
['No' 'Yes']
['No' 'Yes']
['Known' 'Unknown']
['Yes' 'No']
['Yes' 'No']
['No' 'Yes']
['No' 'Yes']
['Yes' 'No']
['Yes' 'No']
[1 0 3 2 4]
[0 1 2 3]
['No' 'Yes']
['No' 'Yes']
[4 5 6 9 1 7 3 0 8 2]
['No' 'Yes']
['Yes' 'No']
['1-Highest' '4-Medium' '3-Good' '6-VeryLow' '2-High' '5-Low' '7-Lowest']
['Suburban' 'Town' 'Other' 'Rural']
['Professional' 'Crafts' 'Other' 'Self' 'Retired' 'Homemaker' 'Clerical'
 'Student']
['No' 'Yes' 'Unknown']


In [21]:
# select only the categorical columns
cat_df = data.select_dtypes(include='int')
# print the column names and the unique values
for col in cat_df.columns:
    print(col)
    print(cat_df[col].unique())


MonthsInService
[61 58 60 59 53 57 55 56 54 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38
 37 36 35 34 33 32 29 31 30 23 24 28 12 27 26 25  8 10 22 19 21 18 20 17
 15 14 16 13 11  9  7  6]
UniqueSubs
[  2   1   3   5   6   4   7  12  11   9   8  10  13  18 196]
ActiveSubs
[ 1  2  3  4  0  5  8  6  9 53 11  7]
RetentionCalls
[1 0 3 2 4]
RetentionOffersAccepted
[0 1 2 3]
ReferralsMadeBySubscriber
[ 0  1  2  3  4  7  5  6 16 11  8  9 35]
IncomeGroup
[4 5 6 9 1 7 3 0 8 2]
AdjustmentsToCreditRating
[ 0  1  3  2  5  4  9  6 10  8  7 11 25 21 12]


In [22]:
import pandas as pd

# apply the type function to each element
types = data.apply(lambda x: x.apply(type))
# get the unique types for each column
for col in types.columns:
    print(col)
    print(types[col].unique())


Churn
[<class 'str'>]
MonthlyRevenue
[<class 'float'>]
MonthlyMinutes
[<class 'float'>]
TotalRecurringCharge
[<class 'float'>]
DirectorAssistedCalls
[<class 'float'>]
OverageMinutes
[<class 'float'>]
RoamingCalls
[<class 'float'>]
PercChangeMinutes
[<class 'float'>]
PercChangeRevenues
[<class 'float'>]
DroppedCalls
[<class 'float'>]
BlockedCalls
[<class 'float'>]
UnansweredCalls
[<class 'float'>]
CustomerCareCalls
[<class 'float'>]
ThreewayCalls
[<class 'float'>]
ReceivedCalls
[<class 'float'>]
OutboundCalls
[<class 'float'>]
InboundCalls
[<class 'float'>]
PeakCallsInOut
[<class 'float'>]
OffPeakCallsInOut
[<class 'float'>]
DroppedBlockedCalls
[<class 'float'>]
CallForwardingCalls
[<class 'float'>]
CallWaitingCalls
[<class 'float'>]
MonthsInService
[<class 'int'>]
UniqueSubs
[<class 'int'>]
ActiveSubs
[<class 'int'>]
ServiceArea
[<class 'str'> <class 'float'>]
Handsets
[<class 'float'>]
HandsetModels
[<class 'float'>]
CurrentEquipmentDays
[<class 'float'>]
AgeHH1
[<class 'float'>]
AgeH

In [12]:
data.select_dtypes(include='object')

Churn ServiceArea ChildrenInHH HandsetRefurbished  \
CustomerID                                                     
3000002      Yes   SEAPOR503           No                 No   
3000010      Yes   PITHOM412          Yes                 No   
3000014       No   MILMIL414          Yes                 No   
3000022       No   PITHOM412           No                 No   
3000026      Yes   OKCTUL918           No                 No   
...          ...         ...          ...                ...   
3399958      Yes   LAXSFN818           No                Yes   
3399974       No   LAXCDG310          Yes                 No   
3399978      Yes   LAXCDG310           No                 No   
3399990       No   NEVPOW619          Yes                 No   
3399994       No   NEVPOW619           No                 No   

           HandsetWebCapable TruckOwner RVOwner Homeownership  \
CustomerID                                                      
3000002                  Yes         No      No         Known   
3000010                   No         No      No         Known   
3000014                   No         No      No       Unknown   
3000022                  Yes         No      No         Known   
3000026                   No         No      No         Known   
...                      ...        ...     ...           ...   
3399958                  Yes         No      No         Known   
3399974                  Yes         No      No         Known   
3399978                  Yes         No      No         Known   
3399990                  Yes         No      No       Unknown   
3399994                  Yes         No      No       Unknown   

           BuysViaMailOrder RespondsToMailOffers  ... HasCreditCard  \
CustomerID                                        ...                 
3000002                 Yes                  Yes  ...           Yes   
3000010                 Yes                  Yes  ...           Yes   
3000014                  No                   No  ...           Yes   
3000022                 Yes                  Yes  ...           Yes   
3000026                 Yes                  Yes  ...           Yes   
...                     ...                  ...  ...           ...   
3399958                 Yes                  Yes  ...           Yes   
3399974                 Yes                  Yes  ...           Yes   
3399978                  No                   No  ...           Yes   
3399990                  No                   No  ...            No   
3399994                  No                   No  ...            No   

           NewCellphoneUser NotNewCellphoneUser OwnsMotorcycle HandsetPrice  \
CustomerID                                                                    
3000002                  No                  No             No           30   
3000010                 Yes                  No             No           30   
3000014                 Yes                  No             No      Unknown   
3000022                 Yes                  No             No           10   
3000026                  No                 Yes             No           10   
...                     ...                 ...            ...          ...   
3399958                  No                  No             No           60   
3399974                  No                  No             No           60   
3399978                  No                  No             No           80   
3399990                  No                  No             No           30   
3399994                  No                  No             No           60   

           MadeCallToRetentionTeam CreditRating PrizmCode    Occupation  \
CustomerID                                                                
3000002                        Yes    1-Highest  Suburban  Professional   
3000010                         No     4-Medium  Suburban  Professional   
3000014                         No       3-Good      Town        Crafts   
30000

In [11]:
correlation_matrix =  data.corr()

ValueError: could not convert string to float: 'Yes'